Update libraries versions
Kotlin/KMP-App-Template-Native pull request #11
Opened 2024-07-09 09:49 UTC by avan1235

2024-07-14 19:50 UTC, zsmb13 approved these changes

2024-07-14 20:35 UTC, zsmb13 requested changes
iOS build is failing for me locally

> clang: error: linker command failed with exit code 1 (use -v to see invocation)

2024-07-15 07:14 UTC, avan1235 commented
I've double-checked locally and it builds fine for me, both with Xcode 15.3 and Xcode 15.4. I used Fleet 1.39.19.
Maybe you have some more details on what attempt `clang` is failing?

2024-09-13 14:51 UTC, zsmb13 commented
I've moved these version upgrades and more into #17

2024-09-13 14:51 UTC, closed without merging